config/routes.rb
Rails.application.routes.draw do
  resources :playlist_drafts
  resources :show_sets
  resources :episode_sets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :show
end

app/models/episode_set.rb
class EpisodeSet < ApplicationRecord
  belongs_to :episode
  belongs_to :playlist_draft
end

app/models/playlist_draft.rb
class PlaylistDraft < ApplicationRecord
  # belongs_to :show_set_id, :foreign_key => 'show_set_id', :class_name => 'ShowSet', :primary_key => 'set_id'
  # belongs_to :episode_set_id, :foreign_key => 'episode_set_id', :class_name => 'EpisodeSet', :primary_key => 'set_id'
  has_many :show_set
  accepts_nested_attributes_for :show_set
  validates_associated :show_set
  has_many :episode_set
  accepts_nested_attributes_for :episode_set
  validates_associated :episode_set
end

app/models/show.rb
class Show < ApplicationRecord
end

app/models/show_set.rb
class ShowSet < ApplicationRecord
  belongs_to :show
  belongs_to :playlist_draft
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episode_sets_controller.rb
# frozen_string_literal: true

class EpisodeSetsController < ApplicationController
  before_action :set_episode_set, only: %i[show edit update destroy]

  def index
    @episode_sets = EpisodeSet.all
  end

  def show; end

  def new
    @episode_set = EpisodeSet.new
  end

  def edit; end

  def create
    @episode_set = EpisodeSet.new(episode_set_params)

    respond_to do |f|
      if @episode_set.save
        f.html { redirect_to @episode_set, notice: 'Episode Set was successfully created.' }
        f.json { render :show, status: :created, location: @episode_set }
      else
        f.html { render :new, status: :unprocessable_entity }
        f.json { render json: @episode_set.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |f|
      if @episode_set.update(episode_set_params)
        f.html { redirect_to @episode_set, notice: 'Episode Set was successfully updated.' }
        f.json { render :show, status: :ok, location: @episode_set }
      else
        f.html { render :edit, status: :unprocessable_entity }
        f.json { render json: @episode_set.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @episode_set.destroy
    respond_to do |f|
      f.html { redirect_to episode_sets_url, notice: 'Episode Set was successfully deleted.' }
      f.json { head :no_content }
    end
  end

  private

  def set_episode_set
    @episode_set = EpisodeSet.find(params[:id])
  end

  def episode_set_params
    params.fetch(:episode_set, {}) #  TODO: fill me out properly later on
  end
end

app/controllers/playlist_drafts_controller.rb
class PlaylistDraftsController < ApplicationController
  before_action :set_playlist_draft, only: %i[ show edit update destroy ]

  # GET /playlist_drafts or /playlist_drafts.json
  def index
    @playlist_drafts = PlaylistDraft.all
  end

  # GET /playlist_drafts/1 or /playlist_drafts/1.json
  def show
  end

  # GET /playlist_drafts/new
  def new
    @playlist_draft = PlaylistDraft.new
    @show_set = @playlist_draft.show_set.build
    # @show_set = @playlist_draft.show_set.build
  end

  # GET /playlist_drafts/1/edit
  def edit
  end

  # POST /playlist_drafts or /playlist_drafts.json
  def create
    @playlist_draft = PlaylistDraft.new(playlist_draft_params)

    if @playlist_draft.save
      params[:show_sets]['number_shows'].each do |a|
        begin
          @show_set = @playlist_draft.show_sets.create!(:number_shows => a)
        rescue ArgumentError
          @playlist_draft.destroy!
          raise ActionController::RoutingError.new('Not Found')
        end

      end
      redirect_to playlist_draft_path(@playlist_draft)
    end
    unless @playlist_draft.save
      # raise ActionController::RoutingError.new('Not Found')
      respond_to do |f|
        f.html { render :new, status: :unprocessable_entity }
        f.json { render json: @playlist_draft.errors, status: :unprocessable_entity }
      end
    end

    # respond_to do |format|
    #   if @playlist_draft.save
    #     format.html { redirect_to @playlist_draft, notice: "Playlist draft was successfully created." }
    #     format.json { render :show, status: :created, location: @playlist_draft }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @playlist_draft.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /playlist_drafts/1 or /playlist_drafts/1.json
  def update
    respond_to do |format|
      if @playlist_draft.update(playlist_draft_params)
        format.html { redirect_to @playlist_draft, notice: "Playlist draft was successfully updated." }
        format.json { render :show, status: :ok, location: @playlist_draft }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playlist_draft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlist_drafts/1 or /playlist_drafts/1.json
  def destroy
    @playlist_draft.destroy
    respond_to do |format|
      format.html { redirect_to playlist_drafts_url, notice: 'Playlist draft was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_playlist_draft
    puts("set callback running...")
    @playlist_draft = PlaylistDraft.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def playlist_draft_params
    params.permit(:title,
                  show_set_attributes: [:id, :set_id, :show_id])
  end
end

app/controllers/show_sets_controller.rb
# frozen_string_literal: true

class ShowSetsController < ApplicationController
  before_action :set_show_set, only: %i[show edit update destroy]

  def index
    @show_sets = ShowSet.all
  end

  def show; end

  def new
    @show_set = ShowSet.new
  end

  def edit; end

  def create
    @show_set = ShowSet.new(show_set_params)

    respond_to do |format|
      if @show_set.save
        format.html { redirect_to @show_set, notice: 'Show Set was successfully created.' }
        format.json { render :show, status: :created, location: @show_set }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @show_set.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @show_set.update(show_set_params)
        format.html { redirect_to @show_set, notice: 'Show Set was successfully updated.' }
        format.json { render :show, status: :ok, location: @show_set }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @show_set.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @show_set.destroy
    respond_to do |format|
      format.html { redirect_to show_sets_url, notice: 'Show Set was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_show_set
    @show_set = ShowSet.find(params[:id]) #  TODO we likely want the other id here
  end

  #  TODO: We will want to actually fill this out eventually.
  def show_set_params
    params.fetch(:show_set, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episode_sets_helper.rb
module EpisodeSetsHelper
end

app/helpers/playlist_drafts_helper.rb
module PlaylistDraftsHelper
end

app/helpers/show_sets_helper.rb
module ShowSetsHelper
end

app/views/episode_sets/_form.html.erb
<%= form_with(model: @episode_set, local: true) do |form| %>
  <% if @show_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show_set.errors.count, "error") %> prohibited this Show Set from being saved:</h2>

      <ul>
        <% @show_set.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

app/views/episode_sets/create.html.erb
<h1>EpisodeSets#create</h1>
<p>Find me in app/views/episode_sets/create.html.erb</p>

app/views/episode_sets/destroy.html.erb
<h1>EpisodeSets#destroy</h1>
<p>Find me in app/views/episode_sets/destroy.html.erb</p>

app/views/episode_sets/edit.html.erb
<h1>EpisodeSets#edit</h1>
<p>Find me in app/views/episode_sets/edit.html.erb</p>

app/views/episode_sets/index.html.erb
<h1>EpisodeSets#index</h1>
<p>Find me in app/views/episode_sets/index.html.erb</p>

app/views/episode_sets/new.html.erb
<h1>EpisodeSets#new</h1>
<p>Find me in app/views/episode_sets/new.html.erb</p>

app/views/episode_sets/show.html.erb
<h1>EpisodeSets#show</h1>
<p>Find me in app/views/episode_sets/show.html.erb</p>

app/views/episode_sets/update.html.erb
<h1>EpisodeSets#update</h1>
<p>Find me in app/views/episode_sets/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StreamingPlaylists</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_packs_with_chunks_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playlist_drafts/_form.html.erb
<%= form_with(model: @playlist_draft, local: true, id: 'new_playlist_form') do |form| %>
  <% if @playlist_draft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist_draft.errors.count, "error") %> prohibited this Playlist Draft from being saved:</h2>

      <ul>
        <% @playlist_draft.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-flex flex-column align-items-center">
    <div class="form-group pt-5 d-flex align-items-center">
      <%= form.label :title, "Playlist Title", class: 'px-4 text-nowrap' %>
      <%= form.text_field :title, { 'data-toggle' => 'tooltip', 'data-placement' => 'top', 'title' => 'Your playlist\'s title', :required => true, :class => "form-control" } %>
    </div>
  </div>

    <%= render :partial => 'show_sets/form', show_set: @show_set %>
  <br/>
  <%#= TODO: Rename submitTest (both as a class and as an ID) wherever it appears both below and in the SCSS %>
  <div class="form-submit-button d-flex justify-content-center">
    <span class="submitTest btn-5" id="submitTest">
      Save Playlist
    </span>
  </div>

  <script>
      window.addEventListener("DOMContentLoaded", function () {
          var form = document.getElementById("new_playlist_form");
          document.getElementById("submitTest").addEventListener("click", function () {
              form.submit();
          });
      });
  </script>
<% end %>

app/views/playlist_drafts/edit.html.erb
<h1>Editing Playlist Draft</h1>

<%= render 'form', playlist_draft: @playlist_draft %>

<%= link_to 'Show', @playlist_draft %> |
<%= link_to 'Back', playlist_drafts_path %>

app/views/playlist_drafts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Playlist Drafts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlist_drafts.each do |playlist_draft| %>
      <tr>
        <td><%= link_to 'Show', playlist_draft %></td>
        <td><%= link_to 'Edit', edit_playlist_draft_path(playlist_draft) %></td>
        <td><%= link_to 'Destroy', playlist_draft, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist Draft', new_playlist_draft_path %>

app/views/playlist_drafts/new.html.erb
<div class="d-flex justify-content-center">
  <h1>New Playlist Draft</h1>
</div>

<%= render 'form', playlist_draft: @playlist_draft %>

<%= link_to 'Back', playlist_drafts_path %>

app/views/playlist_drafts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_playlist_draft_path(@playlist_draft) %> |
<%= link_to 'Back', playlist_drafts_path %>

app/views/show_sets/_form.html.erb
<%= form_with(model: @show_set, local: true) do |form| %>
  <% if @show_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show_set.errors.count, "error") %> prohibited this Show Set from being saved:</h2>

      <ul>
        <% @show_set.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= react_component("Shows") %>
    <%#= TODO: "Add Another Show" button. See the episode button TODO for plan details %>

  <div class="episode-set-form-group">
    <%= render :partial => 'episode_sets/form', episode_set: @episode_set %>
    <%#= TODO: "Add Another Episode" button. Ideally presented below the current episode fields but obviously placing it above the button %>
  </div>

<% end %>

app/views/show_sets/create.html.erb
<h1>ShowSets#create</h1>
<p>Find me in app/views/show_sets/create.html.erb</p>

app/views/show_sets/destroy.html.erb
<h1>ShowSets#destroy</h1>
<p>Find me in app/views/show_sets/destroy.html.erb</p>

app/views/show_sets/edit.html.erb
<h1>ShowSets#edit</h1>
<p>Find me in app/views/show_sets/edit.html.erb</p>

app/views/show_sets/index.html.erb
<h1>ShowSets#index</h1>
<p>Find me in app/views/show_sets/index.html.erb</p>

app/views/show_sets/new.html.erb
<h1>ShowSets#new</h1>
<p>Find me in app/views/show_sets/new.html.erb</p>

app/views/show_sets/show.html.erb
<h1>ShowSets#show</h1>
<p>Find me in app/views/show_sets/show.html.erb</p>

app/views/show_sets/update.html.erb
<h1>ShowSets#update</h1>
<p>Find me in app/views/show_sets/update.html.erb</p>